package com.velora.markets.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Order(1)
public class DatabaseSchemaMigrationRunner implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DatabaseSchemaMigrationRunner.class);

    private final JdbcTemplate jdbcTemplate;

    public DatabaseSchemaMigrationRunner(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {
        try {
            log.info("Checking database schema compatibility...");

            // Check if holdings has legacy UUID or 'shares' column
            Integer legacyHoldings = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'holdings' AND (column_name = 'shares' OR data_type = 'uuid')",
                Integer.class
            );

            if (legacyHoldings != null && legacyHoldings > 0) {
                log.warn("Legacy incompatible holdings table detected. Rebuilding trading tables...");
                jdbcTemplate.execute("DROP TABLE IF EXISTS transactions CASCADE");
                jdbcTemplate.execute("DROP TABLE IF EXISTS orders CASCADE");
                jdbcTemplate.execute("DROP TABLE IF EXISTS holdings CASCADE");
            }

            // Check if orders has legacy UUID or 'client_order_id' column
            Integer legacyOrders = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'orders' AND (column_name = 'client_order_id' OR data_type = 'uuid')",
                Integer.class
            );

            if (legacyOrders != null && legacyOrders > 0) {
                log.warn("Legacy incompatible orders table detected. Rebuilding trading tables...");
                jdbcTemplate.execute("DROP TABLE IF EXISTS transactions CASCADE");
                jdbcTemplate.execute("DROP TABLE IF EXISTS orders CASCADE");
            }

            // Check if transactions has legacy UUID or 'shares' column
            Integer legacyTransactions = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'transactions' AND (column_name = 'shares' OR data_type = 'uuid')",
                Integer.class
            );

            if (legacyTransactions != null && legacyTransactions > 0) {
                log.warn("Legacy incompatible transactions table detected. Rebuilding transactions table...");
                jdbcTemplate.execute("DROP TABLE IF EXISTS transactions CASCADE");
            }

            // Ensure holdings table exists with correct schema
            jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS holdings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    portfolio_id BIGINT NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
                    symbol VARCHAR(20) NOT NULL,
                    quantity INTEGER NOT NULL,
                    average_buy_price NUMERIC(19, 4) NOT NULL,
                    CONSTRAINT uk_holdings_portfolio_symbol UNIQUE (portfolio_id, symbol)
                )
            """);

            // Ensure orders table exists with correct schema
            jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    symbol VARCHAR(20) NOT NULL,
                    company_name VARCHAR(255) NOT NULL,
                    side VARCHAR(10) NOT NULL,
                    order_type VARCHAR(10) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    quantity INTEGER NOT NULL,
                    limit_price NUMERIC(19, 4),
                    execution_price NUMERIC(19, 4),
                    total_amount NUMERIC(19, 4),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    executed_at TIMESTAMP WITH TIME ZONE
                )
            """);

            // Ensure transactions table exists with correct schema
            jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS transactions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
                    symbol VARCHAR(20) NOT NULL,
                    side VARCHAR(10) NOT NULL,
                    quantity INTEGER NOT NULL,
                    price NUMERIC(19, 4) NOT NULL,
                    total_amount NUMERIC(19, 4) NOT NULL,
                    realized_pnl NUMERIC(19, 4),
                    executed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """);

            log.info("Database schema compatibility check completed successfully.");
        } catch (Exception e) {
            log.warn("Database schema compatibility check encountered a non-fatal warning: {}", e.getMessage());
        }
    }
}
